apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ydnz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-ydnz@sha256:ebf6db717d8b1f3acd87a1129658d26acbcf0352747fbf9b60ade1e366b5f9bf
        name: my-nodejs
        resources: {}
status: {}
